### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by Z33DD** [nukeop/hide.py#14]
# See this:

## I'm install all the requirements:

```bash
user@computer:~/Programs/hide.py$ pip install -r requirements.txt --user
/home/user/.local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.2.3)
```
## And I'm give this:

```bash
user@computer:~/Programs/hide.py$ python hide.py
Traceback (most recent call last):
  File "hide.py", line 11, in <module>
    from PIL import Image
ImportError: No module named PIL
```

**Comment by Z33DD** [comment]
## When I'm try install the package with pip, this happens:

```bash
user@computer:~/Programs/hide.py$ pip install PIL
/home/z33dd/.local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

**Comment by nukeop** [comment]
You're using Python 3.5, this script will only run in Python 2.7+.

**Comment by Z33DD** [comment]
# I think that find the problem!

## I try use with Python 2.7, happens the same:

```bash
user@computer:~/Programs/hide.py$ python hide.py
Traceback (most recent call last):
  File "hide.py", line 11, in <module>
    from PIL import Image
ImportError: No module named PIL
user@computer:~/Programs/hide.py$ python --version
Python 2.7.12
```

## It seems the problem is here:

```bash
user@computer:~/Programs/hide.py$ pip install PIL --user
/home/z33dd/.local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

## Pip search for a PIL module to "elementary OS 0.4.1 Loki" rather than "Ubuntu 14", 

```bash
user@computer:~/Programs/hide.py$ cat /etc/*-release
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4.1
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki"
NAME="elementary OS"
VERSION="0.4.1 Loki"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4.1 Loki"
VERSION_ID="0.4.1"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://github.com/elementary/"
VERSION_CODENAME=loki
UBUNTU_CODENAME=loki
cat: /etc/upstream-release: Is a directory
```
### The big question is "**how to download and install the module of another distro with pip?**"

**Comment by nukeop** [comment]
Yes, because pip is aliased to your machine to pip3, use the version for python 2. Better yet, create a virtual environment.

```
$ cd hide.py
$ virtualenv -p python2.7 venv
$ source venv/bin/activate
$ pip install -r requirements.txt
```

Replace `python2.7` with the python2 binary on your system.

**Comment by Z33DD** [comment]
Thanks! It's working now!

Ps: Hey guy, has a error here:
$ source venv/bin/**acitvate**

**Comment by nukeop** [comment]
Right, I corrected it for anyone reading this in the future.
